### ISSUE TITLE
変換中に編集モード左手側の記号が入力できない

### ISSUE THREAD

**Issue by tor-nky** [eswai/Benkei#11]
変換中に、編集モード左手側の記号が入力できません。
空白と改行が入っていると、それには反応しているようです。

**Comment by eswai** [comment]
記号を入力するときに、一旦かなオフにして、UNICODEを送信するのですが、変換途中の文字があると、かながオフにできないからですね。かなモードのままUNICODEは送れないので、問答無用で変換中の文字を確定してしまうしかないのかな？

**Comment by eswai** [comment]
英数モードに切り替えるのに、英数キーではなく、apiで切り替えるようにしたら、変換中文字を確定してから英数モードに変わり、UNICODE入力できました。

**Comment by tor-nky** [comment]
現在、macOS Mojave 10.14.6 で確認され、それ以降のOSでは発生しない現象とみられます。

**Comment by tor-nky** [comment]
macOS Big Sur 11.2.3 にアップグレードしましたが、この現象がなぜかなくなりません。

**Comment by eswai** [comment]
[Benkei_b2.1.1.zip](https://github.com/eswai/Benkei/files/6264790/Benkei_b2.1.1.zip)

これだとどうでしょう。

**Comment by tor-nky** [comment]
これでもダメなので、きっと私の環境だけの問題なんでしょうね。

**Comment by tor-nky** [comment]
解決しました。
英字入力に、「日本語IM」や「かわせみ3」のものを使わないで、「U.S.」を使うようにしたら、かな入力中も記号が打てました。

**Comment by tor-nky** [comment]
「“キーボード”環境設定」にある「U.S.」を残しておけば問題が起きないようです。
