### ISSUE TITLE
IME ON(H+J)とIME OFF(F+G)の繰り返しで

### ISSUE THREAD

**Issue by tor-nky** [eswai/Benkei#13]
かなり快適に使えるようになりましたが、妙なことがありますので報告します。

IME ON(H+J)からすぐIME OFF(F+G)にする繰り返しが、最初は正常で、次から1回でIME OFFにならなくなってきます。
IME ON(H+J)のあと何キーか押してからなら、すぐIME OFFになるんですが、何キー押した後なら良いかは次第に長くなるようです。
(F+G)を2回押すうちには必ずIME OFFになります。

また、(F+G)でIME OFFとし、(H+J)でIME ONとすると、左濁(F)が押されっぱなしになるようです。

もちろん、かなキー、英数キーでIME ON/OFFすれば問題はおきません。

**Comment by tor-nky** [comment]
(F+G)でIME OFFとし、(H+J)でIME ONとすると、左濁(F)が押されっぱなし……は再現性はありませんでした。
なんとMacの再起動で出なくなりました。

**Comment by eswai** [comment]
薙刀式の起動処理って一番悩むところだったので、心当たりはありました。
かなモードじゃない時の処理は、は将来、英数モードでも編集モードを使いたい、となると、根本的に考えないといけないなと、思っています。
