### ISSUE TITLE
記号連打と｜《》

### ISSUE THREAD

**Issue by tor-nky** [eswai/Benkei#16]
編集モードの記号を連打すると、変換が入るようです。例えば、
」「
)」
で起きます。これだけなら直さなくてもいい問題ですが、
｜《》
で変換が入って違う記号になることがあるので、一応確認してください。

**Comment by eswai** [comment]
ありがとうございます。キー入力後にwaitを入れると解決できそうです。

**Comment by tor-nky** [comment]
もしかしたら、かなキーの連打で再変換の扱いになっているのでは。
記号を続けて入力すると変換が入る現象が発生しますが、
　　　記号→シフト+かな(カタカナ入力モード)→記号
だと起きないので。

**Comment by eswai** [comment]
前提の確認ですが、MacOS標準の日本語入力、ローマ字入力でしょうか。

**Comment by tor-nky** [comment]
そうです。日本語-ローマ字入力、ライブ変換なし、Windows風でない、です。

**Comment by tor-nky** [comment]
こちらも同じ方法で解決しました。
英字入力に、「日本語IM」や「かわせみ3」のものを使わないで、「U.S.」を使うようにしたら、かな入力中も記号が打てました。
ご厄介をおかけしました。

**Comment by eswai** [comment]
私も同現象を再現できました。
回避策を探してみます。

**Comment by eswai** [comment]
[Benkei_b2.1.2.zip](https://github.com/eswai/Benkei/files/6268791/Benkei_b2.1.2.zip)
こちら試していただけますでしょうか。

**Comment by tor-nky** [comment]
システム環境設定/キーボード/入力ソース に「U.S.」があれば、ちゃんと動きます。
記号を入力してからは、F+G(英数入力)を押すと「U.S.」になりますし。
(macOS Big Sur 11.2.3 + 日本語IM or かわせみ3 3.0 で確認しました)

「U.S.」は消しておいても何かの拍子に出現する、よくある現象が起きたので、昨日は気づきました。

**Comment by eswai** [comment]
英字入力に、USではなく（USを削除して）「日本語IM」のものをつかっても、手元では正常動作しました。カワセミではどうでしょうか。

**Comment by tor-nky** [comment]
私のところでは、システム環境設定/キーボード/入力ソース に「U.S.」がなければ、日本語IMでも「かわせみ3」でも、未確定のかながあると記号は出せません。

**Comment by tor-nky** [comment]
かつては（１４年以上前）「U.S.」がないと、文字入力に支障が出るソフトを使っていましたので、仕様だと割り切って使うことにします。

**Comment by eswai** [comment]
ありがとうございます。なかなか一筋縄でいきませんね。

**Comment by tor-nky** [comment]
「“キーボード”環境設定」にある「U.S.」を残しておけば問題が起きないようです。
