### ISSUE TITLE
一部のカナに、入力順によって不具合

### ISSUE THREAD

**Issue by tor-nky** [eswai/Benkei#19]
3キー同時押し入力の一部のカナに、3つ目に押すキーが左側になるときだけ正しく入力できないようです。

ぴゃ、ぴょ、てぃ、とぅ、ふぇ、ふゅ、ふぁ、ふぃ、ふぉ、ゔゅ、いぇ、つぇ、つぁ、つぃ、つぉ

たとえば「ぴゃ」のつもりが「なぴゃ」「くぴ」になったりします。私のところだけかもしれませんが……
(macOS Big Sur 11.2.3 + Benkei Beta 2.1.4 + 日本語IM)

**Comment by eswai** [comment]
ありがとうございます。確認できました。

**Comment by eswai** [comment]
b2.1.5で修正しました。変換候補が一つになったらカナに変換してしまうのですが、まだ２キーまでしか押していないのに、候補が一つになる場合に、誤動作していました。

**Comment by tor-nky** [comment]
「ふぇ」「うぇ」のような打ちにくい同時押しは、右手側の２キーを決めてから左手１キーを押すと失敗しにくかったので、とても使いやすくなりました。
