### ISSUE TITLE
v15仮最終候補対応への修正希望

### ISSUE THREAD

**Issue by tor-nky** [eswai/Benkei#24]
以下のかな定義が多分うまく動きません。
* 、{Enter} --改行(確定)が入らない
* スペース+Q --ヴの前に空白が入る
* {Home}{改行}{Space 3}{←}
* {Home}{改行}{Space 1}{←}  
 --ともに{←}が入っていない

**Comment by eswai** [comment]
ありがとうございます。修正を入れました。
以前は、の後にenter入れない仕様でしたが、enter入れるように変更されたのですね。

**Comment by tor-nky** [comment]
そうなんですよね。慣れると使いやすいですよ。

私個人は次の修正をしたものを使わせてもらっています。
* JK+S、M,+S の丸カッコを全角にする
* ^i、^u はそれぞれ F7、F6 にする

あと一応、Naginata.m 内で固有名詞がダブっていました。

**Comment by tor-nky** [comment]
たびたびすみません。
DF+O {Del} がバックスペースになっています。
"{Del}" => ["kVK_ForwardDelete"]
が正しいと思います。

**Comment by eswai** [comment]
どうもありがとうございます。
確認助かります。
