### ISSUE TITLE
あああい

### ISSUE THREAD

**Issue by tor-nky** [eswai/Benkei#6]
J→K→L→semicolon  と押して semicolon→L→K→J の順に離すと「あああい」となる怪現象。
逆に semicolon→L→K→J と押して J→K→L→semicolon の順に離すと「ーういあ」となり正常。

F→D→S→A と押して逆順に離すと「かかかと」。右手と左手で反対みたいですね。

**Comment by eswai** [comment]
連続シフトやオールオーバー時の挙動がまだまだ怪しいですね。
