### ISSUE TITLE
カーソル移動系を縦書き・横書き共通にするには

### ISSUE THREAD

**Issue by tor-nky** [eswai/Benkei#7]
長文になります。

Macだと次のように定義すると、縦書き・横書き共通にできるようです。
左（T）Control+N
右（Y）Control+P
最末尾（J+K+Q）Command+上 からの Command+下
↑（D+F+J）Control+B
↑選択（D+F+K）Shift+Control+B
５↑（D+F+L）Control+B ×５回
↓（D+F+M）Control+F
↓選択（D+F+Period）Shift+Control+F
５↓（D+F+Dot）Control+F ×５回
ルビマクロ（M+Period+W）最後の矢印をControl+Bにする
→５（C+V+J）Control+P ×５回
→５選択（C+V+K）Shift+Control+P ×５回
←５（C+V+M）Control+N ×５回
←５選択（C+V+Period）Shift+Control+N ×５回
ただ、対応しないソフトが多いんです……たとえばMicrosoft Wordが！

ページ移動系はエディタによって違うようですが、PageUp/Downが画面のみ移動なのは共通。
テキストエディット、Jedit Ωは Option+PageUp/Downでさらにカーソルも移動しますが、たとえばegword Universal 2 では方法がありません。

**Comment by eswai** [comment]
これは重要な情報をありがとうございます。使わせていただきます。

**Comment by tor-nky** [comment]
間違えました。正しくは
最末尾（J+K+Q）Command+左 からの Command+下
でした。
他のも見直します。
